<a href="https://colab.research.google.com/github/Viny2030/UMSA-Analisis_de_datos/blob/main/ba_ci_001_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="https://pypi.org/static/images/logo-small.8998e9d1.svg" width="" height="">
</p>

 # **<font color="#07a8ed">Preprocesamiento de los Datos - Codificación e imputaciones</font>**

## **<font color="#07a8ed">Bibliotecas**

### **<font color="#07a8ed">Para análisis de datos**

In [ ]:
import pandas as pd
import numpy as np

### **<font color="#07a8ed">Para preprocesamiento de datos**

In [ ]:
import sklearn
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.impute import KNNImputer

 ## **<font color="#07a8ed">Obtención de los Datos</font>**

In [ ]:
url = "https://raw.githubusercontent.com/cristiandarioortegayubro/BA/main/Datasets/banco.csv"

In [ ]:
analisis = pd.read_csv(url, index_col=0)
analisis.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

 ## **<font color="#07a8ed">Reemplazo de "unknown"</font>**

In [ ]:
analisis.replace({"unknown": None}, inplace=True)

In [ ]:
analisis.head(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,58,management,married,tertiary,no,2143,yes,no,None,5,may,261,1,-1,0,None,no
1,44,technician,single,secondary,no,29,yes,no,None,5,may,151,1,-1,0,None,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,None,5,may,76,1,-1,0,None,no
3,47,blue-collar,married,None,no,1506,yes,no,None,5,may,92,1,-1,0,None,no
4,33,None,single,None,no,1,no,no,None,5,may,198,1,-1,0,None,no
5,35,management,married,tertiary,no,231,yes,no,None,5,may,139,1,-1,0,None,no
6,28,management,single,tertiary,no,447,yes,yes,None,5,may,217,1,-1,0,None,no
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,None,5,may,380,1,-1,0,None,no
8,58,retired,married,primary,no,121,yes,no,None,5,may,50,1,-1,0,None,no
9,43,technician,single,secondary,no,593,yes,no,None,5,may,55,1,-1,0,None,no

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        44923 non-null  object
 2   marital    45211 non-null  object
 3   education  43354 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    32191 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   8252 non-null   object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 6.2+ MB

In [ ]:
analisis.isnull().sum().sort_values(ascending=False)

poutcome     36959
contact      13020
education     1857
job            288
month            0
previous         0
pdays            0
campaign         0
duration         0
age              0
day              0
loan             0
housing          0
balance          0
default          0
marital          0
deposit          0
dtype: int64

## **<font color="#07a8ed">Codificación de variables categóricas</font>**

In [ ]:
convertir = LabelEncoder()

In [ ]:
analisis.insert(2,column="numjob",value = convertir.fit_transform(analisis.job))
analisis.insert(4,column="nummarital",value = convertir.fit_transform(analisis.marital))
analisis.insert(6,column="numeducation",value = convertir.fit_transform(analisis.education))
analisis.insert(8,column="numdefault",value = convertir.fit_transform(analisis.default))
analisis.insert(11,column="numhousing",value = convertir.fit_transform(analisis.housing))
analisis.insert(13,column="numloan",value = convertir.fit_transform(analisis.loan))
analisis.insert(15,column="numcontact",value = convertir.fit_transform(analisis.contact))
analisis.insert(23,column="numpoutcome",value = convertir.fit_transform(analisis.poutcome))

In [ ]:
def mes(month):
  if month == "jan":
    return int("1")
  elif month == "feb":
    return int("2")
  elif month == "mar":
    return int("3")
  elif month == "apr":
    return int("4")
  elif month == "may":
    return int("5")
  elif month == "jun":
    return int("6")
  elif month == "jul":
    return int("7")
  elif month == "aug":
    return int("8")
  elif month == "sep":
    return int("9")
  elif month == "oct":
    return int("10")
  elif month == "nov":
    return int("11")
  else:
    return int("12")

In [ ]:
analisis.month = analisis.month.apply(mes)

 ## **<font color="#07a8ed">Imputación de valores faltantes</font>**

In [ ]:
analisis.head()

,age,job,numjob,marital,nummarital,education,numeducation,default,numdefault,balance,...,numcontact,day,month,duration,campaign,pdays,previous,poutcome,numpoutcome,deposit
0,58,management,4,married,1,tertiary,2,no,0,2143,...,2,5,5,261,1,-1,0,None,3,no
1,44,technician,9,single,2,secondary,1,no,0,29,...,2,5,5,151,1,-1,0,None,3,no
2,33,entrepreneur,2,married,1,secondary,1,no,0,2,...,2,5,5,76,1,-1,0,None,3,no
3,47,blue-collar,1,married,1,None,3,no,0,1506,...,2,5,5,92,1,-1,0,None,3,no
4,33,None,11,single,2,None,3,no,0,1,...,2,5,5,198,1,-1,0,None,3,no

In [ ]:
analisis.job[4]

In [ ]:
analisis.numjob[4]

11

In [ ]:
imputacion = KNNImputer(n_neighbors=3, missing_values=11, weights="uniform")

In [ ]:
analisis.numjob = imputacion.fit_transform(analisis[["numjob"]])

In [ ]:
analisis.numjob = round(analisis.numjob,3)

In [ ]:
analisis.numjob[4]

4.297

In [ ]:
analisis.head()

,age,job,numjob,marital,nummarital,education,numeducation,default,numdefault,balance,...,numcontact,day,month,duration,campaign,pdays,previous,poutcome,numpoutcome,deposit
0,58,management,4.000,married,1,tertiary,2,no,0,2143,...,2,5,5,261,1,-1,0,None,3,no
1,44,technician,9.000,single,2,secondary,1,no,0,29,...,2,5,5,151,1,-1,0,None,3,no
2,33,entrepreneur,2.000,married,1,secondary,1,no,0,2,...,2,5,5,76,1,-1,0,None,3,no
3,47,blue-collar,1.000,married,1,None,3,no,0,1506,...,2,5,5,92,1,-1,0,None,3,no
4,33,None,4.297,single,2,None,3,no,0,1,...,2,5,5,198,1,-1,0,None,3,no